version: "3.8"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: ch
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./ch_data:/var/lib/clickhouse
      - ./ch_logs:/var/log/clickhouse-server
    restart: always
    ports: ["8123:8123","9000:9000"]
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}     
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-my_secret_password}
      - CLICKHOUSE_DEFAULT_USER=${CLICKHOUSE_USER:-default}
